remote_theme: pages-themes/cayman@v0.2.0
title: Ashlie Garcia's Data Analytics Portfolio
description: Hello! Welcome to my Portfolio. You will find a variety of projects that demonstrates data cleaning, data exploratory analysis, and pivot tables. 
