remote_theme: pages-themes/cayman@v0.2.0
title: Ashlie Garcia's Data Analytics Portfolio
description: I am an Academic and Curriculur Analyst pursuing a Master of Science in Data Analytics from Western Governors University. In this portfolio, I have included a variety of projects to showcase my skills. 
